language: node_js
sudo: true
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_script:
  - npm install -g browserify
  - chmod 775 ./test/run_test.sh
  
script: ./test/run_test.sh