var dictionary = {
  " comparer": " comparer la rénaque",
  " c'est à dire": " hein, c'est à dire",
  " c'est-à-dire": " hein, c'est à dire",
  " càd": " hein, c'est à dire",
  " cad": " hein, c'est à dire",
  " valium": " ovarium",
  " variance": " ovariance",
  " test": " essai nucléaristique",
  " tests": " tentatives de diplomatie par l'animal",
  " dynamiser": " incrystaliser",
  " imposer": " intentioner",
  " lois du marché": " congolexicomatisation des lois du marché",
  " de rien": " je vous en prie",
  " rollers": " rowllèr",
  " oui": " mais oui c'est clair",
  " le sport": " la dynamique du sportivisme",
  " les sports": " la dynamique des sports",
  " du sport": " la dynamisation sportive",
  " c'est": " c'est l'activisme",
  " problème": " problème de TGO",
  " théorie": " théorie générale des organisation (TGO)",
  " organisations": " organisations (cf: TGO hein)",
  " le climat": " la climatologie",
  " renaissance": " rénaque, hein,",
  " végétal": " végétalien",
  " végétalien": " végétalisme",
  " le marché": " la congolexicomatisation des lois du marché",
  " du marché": " de la congolexicomatisation des lois du marché",
  " des marchés": " de la congolexicomatisation des lois du marché",
  " système": " système de la technicité informatisée",
  " unicité": " la nucléarité, c'est l'homme qui va vert la dynamique",
  " le nucélaire": " la nucléarité forte",
  " dynamique": " dynamique des peuples",
  " c'est ça": " c'est, ça y fait allusion",
  " vivacité": " rédynamisme de l'homme",
  " assurer": " assurer ce qu'on appelle la systématique de l'orthodoxisation",
  " réflexion": " réflexologie, le réflex, tu sais ça",
  " la pensée": " la relaxation comme tel quand on parle de relaxation",
  " appelle": " appelle l'upensmie qui doit être éventuelle",
  " éventuelle": " éventuelle qui doit être éventualiste",
  " informatique": " informatique du sens dynamiciel",
  " allusion": " allusion à informatiser vers l'humanisme",
  " merci": " je vous en prie",
  " de rien": " oui",
  " programmation": " programmation arbitraire",
  " en avant": " au delà du devant",
  " changements": " évolutions des théories humanisantes",
  " domaine": " domaine de compétences des TGO",
  " naissance": " naissance du paradigme",
  " fortement": " fortement indestructuré des bananes",
  " des données": " di dounies",
  " de données": " di dounies",
  " les données": " li dounies",
  " la donnée": " la douni",
  " incohérent": " in cohérant des actifs",
  " compréhension": " entente forte de la compréhension",
  " paramètre": " paradigme paramétrial, mais c'est clair",
  " augmente": " relaxe la difficulté de l'augmentation",
  " effet de bord": " effet des systémiques",
  " accumuler": " transdiffuser l'accumulation",
  " résultat": " résultante numéricalistique",
  " radicale": " radicalement propre aux théories",
  " par ailleurs": " mais d'ailleurs",
  " d'ailleurs": " mais, c'est clair",
  " technique": " technicité dans l'ovarisme",
  " enfant": " enfant des rollès",
  " effectuer": " effectuer par la rénaque",
  " usage": " usage transfigural",
  " la variation": " la covariance compilatoire",
  " les variations": " des covariances extrajubilatoires",
  " des variations": " des résultantes angulaires",
  " la conception": " la conceptualisation industrielle",
  " OCaml": " au calme",
  " C'est plus": " C++",
  " références": " capacités du savoir",
  ", et": ", et donc",
  "a.": "a, c'est clair.",
  "e.": "e, mais oui.",
  "i.": "i, oui, c'est bien ça.",
  "o.": "o, oui.",
  "u.": "u, évidemment.",
  "y.": "y, de toute évidence.",
  "t.": "t, bien entendu.",
  "r.": "r, par la rénaque !",
  "encore ": "avec conviction, manifestation, ultimisme ",
  "montagne": "motte de terre sur-élevée",
  "présentation": "démonstration ovarique",
  "principalement": "pwouincipallement",
  "permet": "donne la possibilité, la nuuuméricité nécessaire, ce qui permet",
  "nation": "République Démocratique du Congo",
  "boisson alcoolisée" : "boisson à dégénération cellulaire",
  "sopalin" : "papier à effacer",
  "essuie-tout" : "papier à effacer",
  "le saut" : "l’envol aérien",
  "jeu vidéo" : "divertissement par la virtualité des objets",
  "la canette" : "le petit récipient de 33 centilitres, soit très exactement 0,33 L.",
  "la patience" : "l’espoir de la suppression de la file d’attente",
  "le cancer" : "la réduction capillaire",
  "la récursivité" : "la démarche qui fait référence à l'objet de la démarche",
  "à côté": "à proximité immédiate",
  "finalement": "par la fin des rollers",
  "titre": "texte présentationnel",
  "les mathématiques": "la science du savoir logique de la République Démocratique du Congo",
  "l'avatar": "la virtualisation de la personne",
  "culmine": "atteint les lumières",
  "sommet": "haut de l'élément"
  "route": "ligne continuelle",
  "une colline": "un demi-tas de terre congolexifié",
  "les colline": "les demi-tas de terre congolexifiés",
  "la colline": "le demi-tas de terre congolexifié",
  "des colline": "des demi-tas de terre congolexifiés",
  "plaine": "surface plate",
  "une attaque": "une offensive communale",
  "pression": "déformation par contact physitionnel",
  "dramatise": "",
  "concerne": "",
  "de façon à": "",
  "présentation": "",
  "passe": "",
  "température": "températion climatologique",
  "supermarché": "lieu de regroupement des brebis",
  "territoire": "terrain appartenant au chef congolais"
};

function replaceTextOnPage(obj){
  getAllTextNodes().forEach(function(node){
    for (var x in obj) {
      node.nodeValue = node.nodeValue.replace(new RegExp(quote(x), 'g'), obj[x]);
    }
  });
  function getAllTextNodes(){
    var result = [];
    (function scanSubTree(node){
      if(node.childNodes.length)
        for(var i = 0; i < node.childNodes.length; i++)
          scanSubTree(node.childNodes[i]);
      else if(node.nodeType == Node.TEXT_NODE)
        result.push(node);
    })(document);
    return result;
  }
  function quote(str){
    return (str+'').replace(/([.?*+^$[\]\\(){}|-])/g, "\\$1");
  }
}

replaceTextOnPage(dictionary);
